### PR TITLE
Feature/mssql

### PR DESCRIPTION
**Pull request by sbellity**

### CODE REVIEW

**Comment by sbellity** [comment]
Thanks @SMK1085 ! I will review it asap.

2 things : 

- were you able to setup a MSSQL instance running on Azure ? I yes, please share the credentials with me on slack or 1Password
- I see that you added a package-lock.json file to the repo. We usually use yarn for lock files on the connectors.

**Comment by sbellity** [comment]
- make sure the stream is properly close on any mssql server side error
- use a CTE to wrap the request for previewing and limiting results to 100 rows

**Comment by SMK1085** [comment]
@sbellity, you cannot have both yarn.lock and package-lock.json if you want to deploy manually to Heroku. It's either or...

**Comment by michaloo** [comment]
@SMK1085 can we close that in favor of: https://github.com/hull-ships/hull-sql/pull/25 ?

**Comment by SMK1085** [comment]
@michaloo, I have closed this one because it is obsolete. #25 replaced it.

**Pull request closed without merging**
