### PR TITLE
Features/tests

### PR DESCRIPTION
**Pull request by mkawalek**

### CODE REVIEW

**Comment by mkawalek** [comment]
Because previous pull request was not merged, this PR also contains previous one. Should I close this PR and create new branch from develop and then write these tests or You would like to take a look at all these changes one more time ? :)

**Comment by michaloo** [comment]
[hull-sql](https://trello.com/c/RQDn0ibo/1-hull-sql)

**Comment by michaloo** [comment]
[hull-webhooks](https://trello.com/c/8395cJL9/3-hull-webhooks)

**Comment by michaloo** [comment]
[hull-typeform](https://trello.com/c/26mszeCz/12-hull-typeform)

**Pull request merged**
